## Write a Numpy program to compute the multiplication of two given matrixes

In [1]:
import numpy as np
my_array1=np.array([[1,2,3],[1,2,3]])
my_array2=np.array([[1,2,3],[1,2,3]])
print(my_array1*my_array2)


[[1 4 9]
 [1 4 9]]


## Write a NumPy program to compute the determinant of a given square array

In [7]:
import numpy as np
from numpy import linalg as la
a=np.array([[1,0],[1,2]])
print(la.det(a))

2.0


## Write a NumPy program to compute the cross product of two given vectors

In [3]:
import numpy as np
a=[1,2]
b=[5,6]
result=np.cross(a,b)
print(result)

-4


## Write a NumPy program to compute the condition number of a given matrix

In [6]:
import numpy as np
from numpy import linalg as la
a=np.array([[1,2,3],
          [4,5,6]])
result=la.cond(a)
print(f"the condition number is {result}")

the condition number is 12.302245504069205


## Write a NumPy program to compute the inverse of a given matrix

In [10]:
import numpy as np
from numpy import linalg as la
a=np.array([[1,2],
          [4,5]])
result=la.inv(a)
print(f"the inverse is \n{result}")

the inverse is 
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
